name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-shell-tests:
    name: Run Shell Scripts in Tests Folder
    runs-on: ubuntu-latest

    env:
      AZURE_OPENAI_API_ENDPOINT: ${{ secrets.AZURE_OPENAI_API_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
      AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Environment Variables
        run: |
          echo "Verifying environment variables..."
          echo "AZURE_OPENAI_API_ENDPOINT: (Hidden for security)"
          echo "AZURE_OPENAI_API_KEY: (Hidden for security)"
          echo "AZURE_OPENAI_API_VERSION: $AZURE_OPENAI_API_VERSION"
          echo "AZURE_OPENAI_DEPLOYMENT_NAME: $AZURE_OPENAI_DEPLOYMENT_NAME"

      - name: Run Indication Classifier Test
        run: |
          source venv/bin/activate
          bash tests/run_indication_test.sh

      - name: Run Doc Tests
        run: |
          source venv/bin/activate
          bash tests/run_doctest.sh app/core/indication_classifier.py